services:

  postgres:
    image: postgres:16
    container_name: datastore360_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore_password
      POSTGRES_DB: datastore360

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: datastore360_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@datastore360.com
      PGADMIN_DEFAULT_PASSWORD: admin_password

    ports:
      - "5050:80"

    depends_on:
      - postgres


volumes:
  postgres_data: